// src/utils/email/translations/en.ts
import { Translations } from '../types';

/**
 * English translations for the email template
 */
const translations: Translations = {
  // Email general
  'subject': '{tier} Support Plan Onboarding for {company} - Microsoft 365 Administration Setup',
  'greeting': 'Dear {name},',
  'intro1': 'Thank you for choosing {company} as your Microsoft 365 administration partner. We are excited to begin the onboarding process for {clientCompany}.',
  'intro2': 'Below are the important steps to complete your onboarding process. Please review each section carefully and follow the instructions to set up your {tier} Support Plan and the necessary access configurations.',
  'closing': 'Please reply to this email to confirm receipt and let us know if you have any questions or concerns.',
  'regards': 'Best regards,',
  'footer': 'This is an automated message generated by the Microsoft Onboarding Template Generator.',
  
  // Section titles
  'supportPlanTitle': '{tier} SUPPORT PLAN DETAILS',
  'authorizedContactsTitle': 'ACTION REQUIRED: AUTHORIZED CONTACTS',
  'tenantTitle': 'ACTION REQUIRED: TENANT INFORMATION',
  'gdapTitle': 'ACTION REQUIRED: GDAP DELEGATION',
  'rbacTitle': 'ACTION REQUIRED: RBAC CONFIGURATION',
  'conditionalAccessTitle': 'RECOMMENDED: CONDITIONAL ACCESS POLICIES',
  'meetingTitle': 'SCHEDULED: ONBOARDING MEETING',
  'additionalInfoTitle': 'ADDITIONAL INFORMATION',
  
  // Support plan section
  'supportPlanIntro': 'The {tier} Support Plan provides {supportType} with the following features:',
  'supportType.bronze': 'basic support availability for non-urgent cases, with no Critical Situation coverage',
  'supportType.other': 'comprehensive support with Critical Situation coverage',
  'supportTypeLabel': 'Support Type:',
  'supportHoursLabel': 'Support Hours:',
  'severityLevelsLabel': 'Severity Levels:',
  'contactsLabel': 'Authorized Contacts:',
  'tenantsLabel': 'Tenants:',
  'requestsLabel': 'Support Requests:',
  'criticalLabel': 'Critical Situation Support:',
  'yes': 'Yes',
  'no': 'No',
  
  // Contacts section
  'contactsIntro': 'Based on your {tier} Support Plan, you can designate up to {count} authorized contacts for your organization. These contacts will be authorized to submit support requests and approve administrative changes to your Microsoft 365 environment.',
  'contactsRolesIntro': 'We recommend designating individuals for the following roles: {roles}.',
  'contactsInstruction': 'Please complete the following table with the required information for each contact:',
  'contactsNote': 'Note: Your {tier} plan includes {count} authorized contacts. Additional contacts can be managed through our customer portal after initial setup.',
  
  // Table headers
  'numberHeader': '#',
  'firstNameHeader': 'First Name',
  'lastNameHeader': 'Last Name',
  'officePhoneHeader': 'Office Phone',
  'mobilePhoneHeader': 'Mobile Phone',
  'emailHeader': 'Email Address',
  'jobTitleHeader': 'Job Title',
  
  // Meeting section
  'meetingIntro': 'We have scheduled an onboarding meeting to discuss these items in detail and answer any questions you may have:',
  'meetingDate': 'Date: {date}',
  'meetingAttendees': 'Please ensure the appropriate team members can attend this meeting.',
  
  // GDAP section
  'gdapIntro': 'Microsoft now requires partners to use GDAP for secure administrative access. We need to implement this by {deadline}.',
  'gdapRoles': 'We will request the "{roles}" role.',
  'gdapPermission': 'This permission will allow us to provide the support services outlined in our agreement while maintaining security best practices.',
  'gdapInstruction': 'Please visit the following link to approve the GDAP relationship:',
  'gdapLink': 'GDAP Approval Link',
  
  // RBAC section
  'rbacIntro': 'We will configure {groups} to ensure users have the appropriate level of access to your environment based on their job functions.',
  'rbacPermissionBoth': 'This includes both Azure and Microsoft 365 access permissions.',
  'rbacPermissionAzure': 'This includes Azure resources access permissions.',
  'rbacPermission365': 'This includes Microsoft 365 service access permissions.',
  'rbacInstruction': 'Please complete the following steps to configure RBAC permissions:',
  'rbacStep1': 'STEP 1: Install Azure PowerShell',
  'rbacStep1Source': 'Source:',
  'rbacStep2': 'STEP 2: Update the tenant and run the following script',
  'rbacStep2Instruction': 'Copy and paste this complete script into your PowerShell console',
  'rbacScriptHeader': 'PowerShell Script (Copy and paste into PowerShell console)',
  'rbacScreenshot': 'Please send us a screenshot of the result of the above script or let us know if you prefer to schedule a Teams meeting to complete this configuration together.',
  
  // Conditional Access section
  'conditionalAccessIntro': 'We recommend implementing the following security policies for your environment:',
  'mfaPolicy': 'Multi-Factor Authentication (MFA) requirements for all users',
  'locationPolicy': 'Location-based access restrictions',
  'devicePolicy': 'Device compliance policies to ensure only secure devices can access your data',
  'signInPolicy': 'Sign-in risk-based policies to prevent suspicious login attempts'
};

export default translations;